AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EMR Studio - Sample Cluster

Parameters:
  Deployment:
    Type: String
    # Default: DEPLOYMENT_DEFAULT

  # EMR Studio provides this value no matter what. We ignore it
  SubnetId:
    Type: String
    Default: ignore

  ClusterName:
    Type: String
    Default: default

  ClusterCapacityUnits:
    Type: Number
    Description: Amount of compute capacity to provision to the cluster. 1 capacity unit = 4 vCPU and 8-32 GB of memory
    Default: 1

Resources:
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
        - Name: Spark
        - Name: Livy
        - Name: JupyterEnterpriseGateway
        - Name: Hive
      Instances:
        CoreInstanceFleet:
          InstanceTypeConfigs:
            - { InstanceType: m5.xlarge }
            - { InstanceType: c5.xlarge }
            - { InstanceType: r5.xlarge }
          Name: Core
          TargetOnDemandCapacity: 0
          TargetSpotCapacity: !Ref ClusterCapacityUnits
        Ec2SubnetId: !ImportValue infra-vpc-sn-public-a
        EmrManagedMasterSecurityGroup:
          Fn::ImportValue: !Sub ${Deployment}-infra-sg-MasterSecurityGroup
        EmrManagedSlaveSecurityGroup:
          Fn::ImportValue: !Sub ${Deployment}-infra-sg-WorkerSecurityGroup
        MasterInstanceFleet:
          InstanceTypeConfigs:
            - { InstanceType: m5.xlarge }
            - { InstanceType: c5.xlarge }
            - { InstanceType: r5.xlarge }
          Name: Driver
          TargetOnDemandCapacity: 0
          TargetSpotCapacity: 1
        # ServiceAccessSecurityGroup:
        #   Fn::ImportValue: !Sub ${Deployment}-infra-sg-ServiceAccessSecurityGroup
      JobFlowRole:
        Fn::ImportValue: !Sub ${Deployment}-infra-iam-EMRInstanceRoleArn
      LogUri:
        Fn::Sub:
        - 's3://${Bucket}/${Deployment}/emr/'
        - { Bucket: !ImportValue 'infra-buckets-LogBucket' }
      Name: !Sub '${Deployment}-emr-cluster-${ClusterName}'
      ReleaseLabel: emr-6.4.0
      ServiceRole:
        Fn::ImportValue: !Sub ${Deployment}-infra-iam-EMRServiceRoleArn
      Tags:
        - { Key: Name, Value: !Sub '${Deployment}-emr-cluster-${ClusterName}' }
      VisibleToAllUsers: true
